### ISSUE TITLE
Landslide hazard index

### ISSUE THREAD

**Issue by olivegardener** [HotspotStoplight/Climate#2]

**Comment by nlebovits** [comment]
https://iopscience.iop.org/article/10.1088/1755-1315/731/1/012028/meta

https://www.mdpi.com/2072-4292/14/18/4662

https://iopscience.iop.org/article/10.1088/1755-1315/782/2/022025/meta

**Comment by nlebovits** [comment]
https://www.sciencedirect.com/science/article/pii/S0012825220302713#s0135

1) use an RF
2) pick data carefully
3) choose a good DEM

**Comment by nlebovits** [comment]
https://www.sciencedirect.com/science/article/pii/S1674987120300542#undfig1

"Hence, in the data collection step, three important types of data should be considered: DTMs, [geology](https://www.sciencedirect.com/topics/earth-and-planetary-sciences/geology) maps, and rainfall-related data."

Uses:
1) elevation
2) aspect
3) curvature
4) twi
5) slope gradient
6) step duration orographic rainfall intensification factor
7) superficial geology
