### ISSUE TITLE
Heat hazard index

### ISSUE THREAD

**Issue by olivegardener** [HotspotStoplight/Climate#3]

**Comment by nlebovits** [comment]
https://link.springer.com/chapter/10.1007/978-3-031-19059-9_14

https://doi.org/10.3390/rs14164076

**Comment by nlebovits** [comment]
Consider using this data, plus CIMP6 data: https://gee-community-catalog.org/projects/heat-hazard/

https://planetarycomputer.microsoft.com/dataset/cil-gdpcir-cc0

**Comment by olivegardener** [comment]
Determine which metric we are interested in modeling

- [ ]consecutive days over 30 degrees C (chronic heat)
or
- [ ]Median surface temperature (acute heat)
